INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_SPECTROMETER_OUTPUT spectrometer_output)

FIND_PATH(
    SPECTROMETER_OUTPUT_INCLUDE_DIRS
    NAMES spectrometer_output/api.h
    HINTS $ENV{SPECTROMETER_OUTPUT_DIR}/include
        ${PC_SPECTROMETER_OUTPUT_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    SPECTROMETER_OUTPUT_LIBRARIES
    NAMES gnuradio-spectrometer_output
    HINTS $ENV{SPECTROMETER_OUTPUT_DIR}/lib
        ${PC_SPECTROMETER_OUTPUT_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SPECTROMETER_OUTPUT DEFAULT_MSG SPECTROMETER_OUTPUT_LIBRARIES SPECTROMETER_OUTPUT_INCLUDE_DIRS)
MARK_AS_ADVANCED(SPECTROMETER_OUTPUT_LIBRARIES SPECTROMETER_OUTPUT_INCLUDE_DIRS)

